"""Minimal persistence boundary for local Community operators."""

from __future__ import annotations

from typing import Iterable, Protocol, runtime_checkable

from narrowcti.domain.security.operators import OperatorRecord


@runtime_checkable
class OperatorStore(Protocol):
    def has_operators(self) -> bool: ...
    def get_by_id(self, operator_id: str) -> OperatorRecord | None: ...
    def get_by_username(self, username: str) -> OperatorRecord | None: ...
    def list_operators(self) -> tuple[OperatorRecord, ...]: ...
    def create_operator(self, username: str, password_hash: str, roles: Iterable[str]) -> OperatorRecord: ...
    def replace_password_hash(self, operator_id: str, expected_hash: str, new_hash: str) -> bool: ...
    def change_password_hash(self, operator_id: str, expected_hash: str, new_hash: str) -> bool: ...
    def set_password_hash(self, operator_id: str, password_hash: str) -> OperatorRecord: ...
    def set_roles(self, operator_id: str, roles: Iterable[str]) -> OperatorRecord: ...
    def set_enabled(self, operator_id: str, enabled: bool) -> OperatorRecord: ...


__all__ = ["OperatorStore"]
